apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cmp-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: cmp-web                  # 目标pod
  minReplicas: 1                   # 最小pod数量
  maxReplicas: 10                  # 最大pod数据
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 83  #内存使用比例， 超过就增加pod
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80  #cpu使用比例，超过就增加pod
